# Generated by Django 3.1 on 2020-09-01 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vfc', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='marriage',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='webaccount',
            field=models.DecimalField(decimal_places=2, default=25000, max_digits=50),
        ),
    ]
